import { FileTypeIcon } from ".";

export default {
  title: "Components/FileTypeIcon",
  component: FileTypeIcon,
  argTypes: {
    fileType: {
      options: [
        "simple-document",
        "simple-spreadsheet",
        "image-SVG",
        "development-JAVA",
        "image-IMG",
        "document-TXT",
        "development-RSS",
        "development-EXE",
        "document-XLS",
        "image-PNG",
        "development-SQL",
        "simple-PDF",
        "development-HTML",
        "default-spreadsheet",
        "default-code",
        "document-CSV",
        "document-XLSX",
        "image-JPEG",
        "design-AI-illustrator",
        "design-INDD-indesign",
        "media-mp3",
        "archive-RAR",
        "document-PPT",
        "development-JSON",
        "development-DMG",
        "media-MKV",
        "image-GIF",
        "simple-audio",
        "media-WAV",
        "default-audio",
        "simple-empty",
        "image-TIFF",
        "document-DOCX",
        "media-MPEG",
        "design-PSD-photoshop",
        "image-EPS",
        "development-JS",
        "default-PDF",
        "design-AEP-after-effects",
        "media-AVI",
        "default-image",
        "archive-ZIP",
        "simple-folder",
        "development-CSS",
        "design-FIG-figma",
        "image-webp",
        "simple-image",
        "simple-video-02",
        "development-XML",
        "default-document",
        "simple-video-01",
        "default-video-01",
        "document-PPTX",
        "simple-code",
        "document-DOC",
        "document-PDF",
        "media-mp4",
        "default-video-02",
        "image-JPG",
      ],
      control: { type: "select" },
    },
    type: {
      options: ["gray", "solid", "default"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    fileType: "simple-document",
    type: "gray",
    fileTypeImageImgClassName: {},
    fileTypeWrapClassName: {},
    fileTypeClassName: {},
  },
};
